name: Artifact

on: [push]

env:
  ARTEFACT_NAME: myartifact

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        use: actions/checkout@v2
      - name: Upload artifact
        use: actions/upload-artifact@v2\
        with:
          name: ${{ env.ARTEFACT_NAME }}
          path: .
      
    
